// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateCatOperation OperationName = "CreateCat"
	DeleteCatOperation OperationName = "DeleteCat"
	GetCatOperation    OperationName = "GetCat"
	ListCatsOperation  OperationName = "ListCats"
	UpdateCatOperation OperationName = "UpdateCat"
)
