name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Ensure Go bin is in PATH
        shell: powershell
        run: |
          $gobin = go env GOBIN
          if (-not $gobin) {
            $gobin = "$env:USERPROFILE\go\bin"
          }
          Write-Host "GOBIN = $gobin"
          if ($env:PATH -notlike "*$gobin*") {
            Write-Host "Adding GOBIN to PATH"
            [Environment]::SetEnvironmentVariable("PATH", "$gobin;$env:PATH", "Process")
          }
          Write-Host "PATH now: $env:PATH"

      - name: Install Ogen@latest
        shell: powershell
        run: |
          Write-Host ">>> Installing ogen@latest"
          go install github.com/ogen-go/ogen/cmd/ogen@latest
          if (-not (Get-Command ogen.exe -ErrorAction SilentlyContinue)) {
            Write-Error "ogen.exe not found in PATH"
            Exit 1
          }
          Write-Host "✅ Ogen installed: $(ogen version 2>&1)"

      - name: Remove internal\api folder if it exists
        shell: cmd
        run: |
          if exist internal\api (
            rmdir /s /q internal\api
            echo "✔ Removed internal\api"
          ) else (
            echo "INFO: internal\api not found, skipping removal"
          )

      - name: Generate code via Ogen
        shell: powershell
        run: |
          Write-Host ">>> Running: ogen --target internal/api --package api --clean openapi\openapi.yaml"
          ogen --target internal/api --package api --clean openapi\openapi.yaml

      - name: Go mod tidy
        shell: cmd
        run: go mod tidy

      - name: Go fmt
        shell: cmd
        run: |
          go fmt ./...
          echo "✔ go fmt passed"

      - name: Go vet
        shell: cmd
        run: go vet ./...

      - name: Run tests
        shell: cmd
        run: go test ./... -v -timeout 30s
