name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Go fmt
        run: go fmt ./...

      - name: Go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./... -v -timeout 30s
